amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456

postgres:
  username: ${DB_POSTGRES_USERNAME:username}
  password: ${DB_POSTGRES_PASSWORD:password}
  schema: adm_videos
  url: ${DB_POSTGRES_URL:localhost:5432}

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2

spring:
  jpa:
    show-sql: false