postgres:
  username: ${DB_POSTGRES_USERNAME:username}
  password: ${DB_POSTGRES_PASSWORD:password}
  schema: adm_videos
  url: ${DB_POSTGRES_URL:localhost:5432}

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2