version: '3.9'

services:
  admin-do-catalogo:
    container_name: admin-do-catalogo
    build:
      context: .
      dockerfile: Dockerfile
    image: lukinhasssss/admin-do-catalogo
    ports:
      - "8080:8080"
    networks:
      - adm_videos_network
    restart: on-failure
    depends_on:
      - postgres-admin-do-catalogo
    environment:
      SPRING_PROFILES_ACTIVE: "production"
      DB_POSTGRES_URL: "postgres-admin-do-catalogo:5432"
      DB_POSTGRES_USERNAME: "lukinhasssss"
      DB_POSTGRES_PASSWORD: "348t7y30549g4qptbq4rtbq4b5rq3rvq34rfq3784yq23847yqor78hvgoreiuvn"
      DB_POSTGRES_SCHEMA: "adm_videos"
      FLYWAY_DB: "jdbc:postgresql://postgres-admin-do-catalogo:5432/adm_videos"
      FLYWAY_USER: "lukinhasssss"
      FLYWAY_PASSWORD: "348t7y30549g4qptbq4rtbq4b5rq3rvq34rfq3784yq23847yqor78hvgoreiuvn"

  postgres-admin-do-catalogo:
    container_name: adm_videos_postgres
    image: postgres:latest
#    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    ports:
      - "5432:5432"
    networks:
      - adm_videos_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-password}
      POSTGRES_DB: ${POSTGRES_DB-adm_videos}

  prometheus-admin-do-catalogo:
    container_name: prometheus-admin-do-catalogo
    image: prom/prometheus
    volumes:
      - ./infrastructure/src/main/resources/prometheus/data:/prometheus
      - ./infrastructure/src/main/resources/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - adm_videos_network
    restart: always

#  grafana:
#    image: grafana/grafana
#    user: "472"
#    depends_on:
#      - prometheus
#    ports:
#      - "3000:3000"
#    networks:
#      - adm_videos_network
#    volumes:
#      - ./infrastructure/src/main/resources/grafana/provisioning/:/etc/grafana/provisioning/
#      - grafana_data:/var/lib/grafana
##    env_file:
##      - ./grafana/config.monitoring
#    restart: always

#  nginx-admin-do-catalogo:
#    container_name: nginx-admin-do-catalogo
#    image: nginx
#    build:
#      context: ./infrastructure/src/main/resources/nginx
#    ports:
#      - '80:80'
#    depends_on:
#      - admin-do-catalogo
#    networks:
#      - adm_videos_network
#    restart: always

networks:
  adm_videos_network: