version: '3.9'

services:
  admin-do-catalogo:
    container_name: admin-do-catalogo
    build:
      context: .
      dockerfile: Dockerfile
    image: lukinhasssss/admin-do-catalogo
    ports:
      - "8080:8080"
    networks:
      - adm_videos_network
    restart: on-failure
    depends_on:
      - postgres-admin-do-catalogo
    environment:
      SPRING_PROFILES_ACTIVE: "production"
      DB_POSTGRES_URL: "postgres-admin-do-catalogo:5432"
      DB_POSTGRES_USERNAME: "lukinhasssss"
      DB_POSTGRES_PASSWORD: "348t7y30549g4qptbq4rtbq4b5rq3rvq34rfq3784yq23847yqor78hvgoreiuvn"
      DB_POSTGRES_SCHEMA: "adm_videos"
      FLYWAY_DB: "jdbc:postgresql://postgres-admin-do-catalogo:5432/adm_videos"
      FLYWAY_USER: "lukinhasssss"
      FLYWAY_PASSWORD: "348t7y30549g4qptbq4rtbq4b5rq3rvq34rfq3784yq23847yqor78hvgoreiuvn"

  postgres-admin-do-catalogo:
    container_name: adm_videos_postgres
    image: postgres:latest
#    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    ports:
      - "5432:5432"
    networks:
      - adm_videos_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-password}
      POSTGRES_DB: ${POSTGRES_DB-adm_videos}

  prometheus-admin-do-catalogo:
    container_name: prometheus-admin-do-catalogo
    image: prom/prometheus
#    user: "1000" # use command 'id -u' for get user id
    volumes:
      - prometheus_data:/prometheus
      - ./infrastructure/src/main/resources/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./infrastructure/src/main/resources/prometheus/alert_rules.yaml:/etc/prometheus/alert_rules.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - adm_videos_network
    restart: always

  alertmanager-admin-do-catalogo:
    container_name: alertmanager-admin-do-catalogo
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./infrastructure/src/main/resources/alertmanager/:/etc/alertmanager/:ro
    networks:
      - adm_videos_network
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yaml'
      - '--storage.path=/alertmanager'
    depends_on:
      - prometheus-admin-do-catalogo

  grafana-admin-do-catalogo:
    container_name: grafana-admin-do-catalogo
    image: grafana/grafana
#    user: "1000" # use command 'id -u' for get user id
    depends_on:
      - alertmanager-admin-do-catalogo
    ports:
      - "3000:3000"
    networks:
      - adm_videos_network
    volumes:
      - grafana_data:/var/lib/grafana
#      - ./infrastructure/src/main/resources/grafana/provisioning/:/etc/grafana/provisioning/
#    env_file:
#      - ./grafana/config.monitoring
    restart: always

  ### START OF ELASTIC STACK CONTAINERS ###

  elasticsearch-admin-do-catalogo:
    container_name: elasticsearch-admin-do-catalogo
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    environment:
      - node.name=elasticsearch-admin-do-catalogo
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - adm_videos_network

  kibana-admin-do-catalogo:
    container_name: kibana-admin-do-catalogo
    image: docker.elastic.co/kibana/kibana:8.6.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-admin-do-catalogo:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch-admin-do-catalogo:9200"]'
    networks:
      - adm_videos_network

  metricbeat-admin-do-catalogo:
    container_name: metricbeat-admin-do-catalogo
    image: docker.elastic.co/beats/metricbeat:8.6.0
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infrastructure/src/main/resources/elasticstack/beats/metricbeat.yaml:/usr/share/metricbeat/metricbeat.yml
    command:
      - '-strict.perms=false'
    restart: on-failure
    depends_on:
      - kibana-admin-do-catalogo
    networks:
      - adm_videos_network

  heartbeat-admin-do-catalogo:
    container_name: heartbeat-admin-do-catalogo
    image: docker.elastic.co/beats/heartbeat:8.6.0
    volumes:
      - ./infrastructure/src/main/resources/elasticstack/beats/heartbeat.yaml:/usr/share/heartbeat/heartbeat.yml
    command:
      - '-strict.perms=false'
    environment:
      - setup.kibana.host=kibana-admin-do-catalogo:5601
    depends_on:
      - kibana-admin-do-catalogo
    networks:
      - adm_videos_network

  apm-admin-do-catalogo:
    container_name: apm-admin-do-catalogo
    image: docker.elastic.co/apm/apm-server:7.17.8
    volumes:
      - ./infrastructure/src/main/resources/elasticstack/apm/apm-server.yaml:/usr/share/apm-server/apm-server.yml
    command:
      - '-strict.perms=false'
    ports:
      - "8200:8200"
    restart: on-failure
    networks:
      - adm_videos_network

  filebeat-admin-do-catalogo:
    container_name: filebeat-admin-do-catalogo
    image: docker.elastic.co/beats/filebeat:8.6.0
    user: root
    networks:
      - adm_videos_network
    volumes:
      - ./infrastructure/src/main/resources/elasticstack/filebeat/filebeat.yaml:/usr/share/filebeat/filebeat.yml
      - ./infrastructure/src/main/resources/elasticstack/filebeat/filebeat.yaml:/etc/filebeat/filebeat.yml
#      - ./infrastructure/src/main/resources/logs:/var/log
#      - ./infrastructure/src/main/resources/logs/application.log:/var/log/application.log
#      - ./infrastructure/src/main/resources/logs/application.log:/var/log/app_logs/application.log
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch-admin-do-catalogo:9200
    command:
      - '-strict.perms=false'

#  logstash-admin-do-catalogo:
#    container_name: logstash-admin-do-catalogo
#    image: docker.elastic.co/logstash/logstash:8.6.0
##    volumes:
##      - ./logstash/logstash.conf:/etc/logstash/conf.d
#    environment:
#      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
#      - ELASTICSEARCH_HOST=http://elasticsearch-admin-do-catalogo:9200
#    depends_on:
#      - elasticsearch-admin-do-catalogo
#    networks:
#      - adm_videos_network

  ### END OF ELASTIC STACK CONTAINERS ###

  nginx-admin-do-catalogo:
    container_name: nginx-admin-do-catalogo
    build: ./infrastructure/src/main/resources/nginx # dcu -d --build nginx-admin-do-catalogo
    ports:
      - '80:80'
    depends_on:
      - admin-do-catalogo
    networks:
      - adm_videos_network

networks:
  adm_videos_network:

volumes:
  prometheus_data:
  grafana_data:
  elasticsearch_data:
  filebeat_data:
