version: '3.9'

services:
  app:
    container_name: admin-do-catalogo
    build:
      context: .
      dockerfile: Dockerfile
    image: lukinhasssss/admin-do-catalogo
    ports:
      - "8080:8080"
    networks:
      - adm_videos_network
    restart: on-failure
    depends_on:
      - postgres-admin-do-catalogo
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      DB_POSTGRES_URL: "postgres-admin-do-catalogo"
      DB_POSTGRES_USERNAME: "lukinhasssss"
      DB_POSTGRES_PASSWORD: "348t7y30549g4qptbq4rtbq4b5rq3rvq34rfq3784yq23847yqor78hvgoreiuvn"
      DB_POSTGRES_SCHEMA: "adm_videos"
      FLYWAY_DB: "jdbc:postgresql://postgres-admin-do-catalogo:5432/adm_videos"
      FLYWAY_USER: "lukinhasssss"
      FLYWAY_PASSWORD: "348t7y30549g4qptbq4rtbq4b5rq3rvq34rfq3784yq23847yqor78hvgoreiuvn"

  postgres-admin-do-catalogo:
    container_name: adm_videos_postgres
    image: postgres:latest
#    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    ports:
      - "5432:5432"
    networks:
      - adm_videos_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-password}
      POSTGRES_DB: ${POSTGRES_DB-adm_videos}

networks:
  adm_videos_network: