--alter table categories replica IDENTITY FULL;
--
--alter table genres replica IDENTITY FULL;
--alter table genres_categories replica IDENTITY FULL;
--
--alter table cast_members replica IDENTITY FULL;
--
--alter table videos_video_media replica IDENTITY FULL;
--alter table videos_image_media replica IDENTITY FULL;
--alter table videos replica IDENTITY FULL;
--alter table videos_categories replica IDENTITY FULL;
--alter table videos_genres replica IDENTITY FULL;
--alter table videos_cast_members replica IDENTITY FULL;