version: '3.9'

services:
  jaeger-codeflix:
    container_name: jaeger-codeflix
    image: jaegertracing/opentelemetry-all-in-one
    ports:
      - "14250:14250"
      - "14268:14268"
      - "6831:6831/udp"
      - "16686:16686"
      - "16685:16685"
    environment:
      - COLLECTOR_OLTP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus-codeflix:9090
#    volumes:
#      - ./jaeger/jaeger-ui.json:/etc/jaeger/jaeger-ui.json
#    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    networks:
      - open-telemetry-codeflix
      - admin-do-catalogo
      - admin-do-catalogo-services
      - monitoramento-codeflix

  otel-collector-codeflix:
    container_name: otel-collector-codeflix
    image: otel/opentelemetry-collector
    ports:
      - "1888:1888"   # pprof extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command:
      - "--config=/etc/otel-collector-config.yaml"
    depends_on:
      - jaeger-codeflix
    networks:
      - open-telemetry-codeflix
      - monitoramento-codeflix
      - admin-do-catalogo
      - admin-do-catalogo-services

networks:
  open-telemetry-codeflix:
    external: true
  monitoramento-codeflix:
    external: true
  admin-do-catalogo:
    external: true
  admin-do-catalogo-services:
    external: true
