version: '3.9'

name: app-admin-do-catalogo

services:
  admin-do-catalogo:
    container_name: admin-do-catalogo
    build:
      context: ../../
      dockerfile: Dockerfile
#    image: lukinhasssss/admin-do-catalogo
    ports:
      - "8080:8080"
    env_file:
      - ../../.env
    restart: on-failure
    networks:
      - admin-do-catalogo
      - admin-do-catalogo-services
#      - open-telemetry-codeflix
#      - elasticsearch-codeflix
    labels:
      filebeat_collector: true

  filebeat-admin-do-catalogo:
    container_name: filebeat-admin-do-catalogo
    image: docker.elastic.co/beats/filebeat:8.12.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro                                                     # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                                                                 # Additional information about containers
      - ./filebeat/filebeat.yaml:/usr/share/filebeat/filebeat.yml:ro  # Configuration file
      - filebeat-admin-do-catalogo:/usr/share/filebeat/data:rw                                                       # Persistence data
    user: root                                                                                                       # Allow access to log files and docker.sock
    environment:
      - ELASTIC_HOSTS=http://elasticsearch-codeflix:9200
      - KIBANA_HOSTS=http://kibana-codeflix:5601
      - LOGSTASH_HOSTS=http://logstash-codeflix:9600
    restart: on-failure
    command:
      - '-strict.perms=false'
    networks:
      - admin-do-catalogo
      - elasticsearch-codeflix

volumes:
  filebeat-admin-do-catalogo:
    external: true

networks:
  admin-do-catalogo:
    external: true
  admin-do-catalogo-services:
    external: true
  open-telemetry-codeflix:
    external: true
  elasticsearch-codeflix:
    external: true
