filebeat:
  autodiscover:
    providers:
      - type: docker
        labels.dedot: true
        templates:
          - condition:
              contains:
                container.labels.filebeat_collector: "true"
            config:
              - type: container
                format: docker
                paths:
                  - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
                processors:
                  - decode_json_fields:
                      when.equals:
                        docker.container.labels.decode_log_event_to_json_object: "true"
                      fields: ["message"]
                      target: ""
                      overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch-codeflix:9200"]

setup:
  kibana:
    host: "kibana-codeflix:5601"
  dashboards:
    enabled: true

logging.metrics.enabled: false



#filebeat:
#  autodiscover:
#    providers:
#      - type: docker
#        labels.dedot: true
#        templates:
#          - condition:
#              contains:
#                container.labels.filebeat_collector: "true"
#            config:
#              - type: container
#                format: docker
#                paths:
#                  - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
#                processors:
#                  - decode_json_fields:
#                      when.equals:
#                        docker.container.labels.decode_log_event_to_json_object: "true"
#                      fields: ["message"]
#                      target: ""
#                      overwrite_keys: true
#  modules:
#    - module: postgresql
#      log:
#        enabled: true
#setup:
#  kibana:
#    host: "kibana-admin-do-catalogo:5601"
#  dashboards:
#    enabled: true
#
#output:
#  logstash:
#    hosts: ["logstash-admin-do-catalogo:5044"]
##  elasticsearch:
##    hosts: [ "elasticsearch-admin-do-catalogo:9200" ]
##    username: "elastic"
##    password: "changeme"
#
#logging:
#  metrics:
#    enabled: false
#
#processors:
#  - add_host_metadata:
#      when.not.contains.tags: forwarded
#  - add_cloud_metadata: ~
#  - add_docker_metadata: ~
#  - add_kubernetes_metadata: ~