heartbeat.monitors:
  - type: http
    schedule: '@every 5s'
    urls:
      - http://elasticsearch-admin-do-catalogo:9200
      - http://kibana-admin-do-catalogo:5601
      - http://admin-do-catalogo:8080/api

  - type: icmp
    schedule: '@every 5s'
    hosts:
      - elasticsearch-admin-do-catalogo
      - kibana-admin-do-catalogo
      - apm-admin-do-catalogo
      - metricbeat-admin-do-catalogo

processors:
  - add_cloud_metadata: ~

#output.logstash:
#  hosts: 'logstash-admin-do-catalogo:5044'

output.elasticsearch:
  hosts: 'elasticsearch-admin-do-catalogo:9200'
  username: 'elastic' # elasticsearch default user
  password: 'changeme'  # elasticsearch default password