version: '3.9'

services:
  prometheus-codeflix:
    container_name: prometheus-codeflix
    image: prom/prometheus
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yaml:/etc/prometheus/alert_rules.yaml
      - prometheus-data-codeflix:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitoramento-codeflix
      - admin-do-catalogo

  alertmanager-codeflix:
    container_name: alertmanager-codeflix
    image: prom/alertmanager
    ports:
      - "9093:9093"
    depends_on:
      - prometheus-codeflix
    restart: unless-stopped
    volumes:
      - ./alertmanager/:/etc/alertmanager/:ro
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yaml'
      - '--storage.path=/alertmanager'
    networks:
      - monitoramento-codeflix

  grafana-codeflix:
    container_name: grafana-codeflix
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus-codeflix
    restart: always
    volumes:
      - grafana-data-codeflix:/var/lib/grafana
    networks:
      - monitoramento-codeflix

networks:
  monitoramento-codeflix:
    external: true
  admin-do-catalogo:
    external: true

volumes:
  prometheus-data-codeflix:
  grafana-data-codeflix:
